apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password
        - name: MYSQL_DATABASE
          value: database1
        resources: {}
        volumeMounts:
        - name: mysql-persistent-storage  
          mountPath: "/var/lib/mysql"
      volumes:
      - name: mysql-persistent-storage    
        persistentVolumeClaim:
          claimName: mysql-persistent-storage
status: {}
