apiVersion: v1
kind: PersistentVolume
metadata:
  name: project-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /nfsdata
    server: 172.31.62.159
  persistentVolumeReclaimPolicy: Retain
